version: '3.5'

services:
  app:
    build: .
    container_name: express-typescript-demo
    environment:
      - NODE_ENV=production
    ports:
      - "0.0.0.0:3000:3000"

networks:
  default:
    name: express-typescript-demo
